import localFont from "next/font/local";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="antialiased h-screen w-full flex items-center justify-center"
      >
        {children}
      </body>
    </html>
  );
}
